version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - Health-Education-England/full-stack

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - Health-Education-England/full-stack
      - Health-Education-England/operations
