name: PR Analysis

on:
  pull_request:
    branches:
      - master

jobs:
  analysis:
    name: Analyse PR
    uses: health-education-england/.github/.github/workflows/pr-analysis-gradle.yml@main
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
