name: Purge Old Artifacts

on:
  repository_dispatch:
    types: [purge_artifacts]
  schedule:
    - cron: '0 1 * * *'

jobs:
  purge:
    name: Purge Artifacts
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Purge
        uses: c-hive/gha-remove-artifacts@v1.1.0
        with:
          age: '7 days'
